### ISSUE TITLE
Versions not matching on deploy script

### ISSUE THREAD

**Issue by sanzeeb3** [sanzeeb3/internet-connection-status#1]
The version in the plugin main file and stable tag in readme.txt is not matching while compared. And so the script exits with:

> Versions don't match. Exiting....

While the stable tag version of readme.txt prints, the version in the plugin's main file is not printing in the command line and is therefore not matching.

https://github.com/sanzeeb3/internet-connection-status/blob/5f36e2010dde2f40a2562175349d0fb5f2267211/deploy.sh#L30

**Comment by sanzeeb3** [comment]
It seems the `* Version: 1.1.1` line should only be `Version: 1.1.1` for the line `grep "^Version" $GITPATH/$MAINFILE | awk '{ print $NF}'` to get the value.

**Comment by sanzeeb3** [comment]
reopening because something isn't accurate. Last time in version 1.2.0, the newly added file wasn't pushed to SVN while the existing files with changes were pushed to svn.

**Comment by shivapoudel** [comment]
@sanzeeb3 Rather than deploy shell script you can better utilize Github action workflow to ship plugin to wp.org using this action https://github.com/10up/action-wordpress-plugin-deploy :)

**Comment by sanzeeb3** [comment]
Thanks @shivapoudel.

**Comment by sanzeeb3** [comment]
Closing in favour of [GH action](https://github.com/sanzeeb3/internet-connection-status/actions/workflows/plugin-deploy.yml)
